### ISSUE TITLE
Permissions TODO

### ISSUE THREAD

**Issue by Malkierian** [ForgeEssentials/ForgeEssentials#1063]
- [x] Add `/p group <GROUP> priority <PRIO>` with applicable parameter shortcuts
- [x] Sort permission nodes in flatfiles
- [x] Add group inheritance
- ~~Add prefix/suffix priority~~  
  There was no need for prefix/suffix priorities yet.  
  If, sometime, we really find a situation where we need this, we can implement it then
- [ ] Paged display of list-commands in `/feperm` (create helper-function for paged-commands)
