### ISSUE TITLE
[WIP] [Scripting] New JS based scripting roadmap

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#2165]
We are currently working at a completely new scripting interface which will be JS based and replace the old scripting system asap. It will provide probably all features you could imagine, as it works with Java JS Engine nashorn (on Java 8) or Rhino (< Java 8) plus a simple access layer between JS and MC / FE.

Features:

- [x] Calling commands from JS
- [x] Getting command arguments in JS
- [x] Command to call scripts from MC
- [ ] Access layers
  - [ ] EntityPlayer
  - [ ] ICommandSender
  - [ ] Permissions
  - [ ] World manipulation (WorldServer, setBlock, etc.)
  - [ ] Server administration (kick, ban, difficulty, etc.)
- [ ] Handle MC events with scripts

**Comment by PitchBright** [comment]
Requesting "CustomServerItems" mod support/integration with the new scripting system, please.

**Comment by Techjar** [comment]
What?

**Comment by luacs1998** [comment]
@techjar https://github.com/ForgeEssentials/CustomServerItems

**Comment by spacebuilder2020** [comment]
hmn... That mod has not been updated in 11 months.

Did not even know it existed.

**Comment by olee** [comment]
Oh yeah I made this one and it is really useful for server customization. Though it could really need an update to 1.8.9 and 1.10.2.

This also sounds like a perfect test case for script integration with other mods.

**Comment by olee** [comment]
We are pretty close to finishing the first stable version of this new feature now.
Lots of wrappers have been added and a lot of stuff can already be done with the new scripting.
After a bit more work on the script upgrading to handle all old script methods / -arguments, this will be closed and we will start on making improvements / adding new features.

**Comment by Zethalion** [comment]
I suggest to open a second issue tracker for scripting only issues.
